#%RAML 1.0
title: API Design Work Exercise
baseUri: http://api.workexercise.com/{version}
mediaType: application/json
protocols: HTTP
version: v0.1
documentation:
  - title: Work Exercise
    content: Felipe Caldas' API design.

types:
  Customer: !include libraries/Customer.dataType.raml

traits:
  contentCacheable: !include libraries/content-cacheable.trait.raml
  traceable:
    headers:
      X-Tracker:
        description: A code to track API calls end to end
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
        example: 12345678-1234-1234-1234-123456789012

/customer:
  get:
    description: List all customers
    is: [ contentCacheable ]
    responses:
      200:
        body:
          type: Customer[]
          example: !include examples/customers.json
      404:
        body:
          properties:
            error:
  /{customer_id}:
    description: A specific customer, identified by its id
    uriParameters:
      customer_id:
        type: number
        example: 1
    get:
      responses:
        200:
          body:
            type: Customer
            example: !include examples/customer.json
        404:
    put: #put is idempotent, so it is a good idea to implement this for {customer_id} to guarantee an object won't be inserted/updated more than once.
      description: Update one particular customer
      body:
        type: Customer
    delete:
      description: Delete one particular customer
      is: [ traceable ]
      responses:
        204:
  post:
    description: Creates one new customer
    is: [ traceable ]
    body:
      type: Customer
    responses:
      201:
        body:
          properties:
