#%RAML 1.0 DataType

#usage: provides a type that stores customer information
description: A simple customer

type: object
properties:
  firstname:  string
  lastname:   string
  addresses:
    type:   array
    items:  !include Address.dataType.raml
